CREATE ROLE vos_api_v4 WITH LOGIN PASSWORD 'vos_api_v4';
GRANT SELECT, UPDATE ON ALL TABLES IN SCHEMA public TO vos_api_v4;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE ON TABLES TO vos_api_v4;